mac_apps:
  - id: 411213048
    name: LadioCast
  - id: 682658836
    name: GarageBand
  - id: 409201541
    name: Pages
  - id: 409203825
    name: Numbers
  - id: 409183694
    name: Keynote
  - id: 497799835
    name: Xcode
  - id: 450527929
    name: Djay
  - id: 414298354
    name: ToyViewer

