- name: Apply macOS defaults
  include_tasks: defaults.yml
  tags: [defaults, system]

- name: Install Homebrew packages
  include_tasks: homebrew.yml
  tags: [homebrew, packages]

- name: Install Mac App Store apps
  include_tasks: mas.yml
  tags: [mas, packages]
